# https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action
# cf. https://github.com/sandrokeil/docker-files/tree/master/gource
# cf. https://superuser.com/questions/556029/how-do-i-convert-a-video-to-gif-using-ffmpeg-with-reasonable-quality

name: Testing gource

on:
    push:
        branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        # cf. https://github.com/actions/virtual-environments/issues/228#issuecomment-637362224
        runs-on: ubuntu-latest
        name: Setting up gource
        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - uses: actions/checkout@v2
            - name: Install gource & xvfb and other deps
              run: sudo apt-get install gource xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 -y
            - name: Install ffmpeg & gifski
              run: sudo apt-get update && sudo snap install ffmpeg gifski
            - name: Run gource with xvfb
              env:
                  CI: true
              run: xvfb-run -a gource -f -1280x720 -o - | ffmpeg -y -r 60 -f image2pipe -vcodec ppm -i - -vcodec libx264 -preset ultrafast -pix_fmt yuv420p -crf 1 -threads 0 -bf 0 gource.mp4
            - name: create frames dir
              run: mkdir frames
            - name: Create images from video & del video
              run: ffmpeg -i ./gource.mp4  -r 5 frames/%04d.png && rm ./gource.mp4
            - name: del old gif & Create gif from images & del frames
              run: rm -f ./gource.gif && gifski -o gource.gif ./frames/*.png && rm -rf ./frames
            - name: List directory contents
              run: sudo find .
            # Shows how to push the generated GIF into the repository
            # We don't want to do this here, per
            # https://homes.cs.washington.edu/~mernst/advice/version-control.html#Dont_commit_generated_files
            # but might still be useful if there is no better option
            - name: Setup git
              uses: mikeal/publish-to-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH_NAME: 'main' #optional defaults to master
            - name: Cleanup xvfb pidx
              uses: bcomnes/cleanup-xvfb@v1
