# re run

name: 'Re run'

on:
    workflow_run:
        workflows: ['Testing gource']
        branches: [main]
        types:
            - completed
            - requested
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build:
        # cf. https://github.com/actions/virtual-environments/issues/228#issuecomment-637362224
        runs-on: ubuntu-latest
        name: Setting up gource

        steps:
            - uses: actions/checkout@v2
            - name: list dir
              run: sudo find .